menu:
    首页: /
    归档: /archives/
    微博: http://weibo.com/xxl2012
    GitHub: https://github.com/foojolt
    Rss: /atom.xml

favicon: /foojolt.jpeg
logo: /foojolt.jpeg

# Comment
# e.g disqus: seansun
disqus:
duoshuo: foojolt

# Analytics
# google-analytics:
ga: UA-74439863-1
# baidu-analytics:
ba: //hm.baidu.com/hm.js?903647bb2221f65fb515f136517cc37f

# Copyright Infomation
startyear: 2015

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: true
